export const NAME_COUNTRY_ORDERDATE_ROWS = [
  {
    name: "John Doe",
    country: "USA",
    orderDate: "2024-01-02",
    id: "1",
    logLabel: "John Doe",
  },
  {
    name: "Jane Smith",
    country: "USA",
    orderDate: "2024-01-11",
    id: "2",
    logLabel: "Jane Smith",
  },
  {
    name: "Alice Johnson",
    country: "USA",
    orderDate: "2024-01-04",
    id: "3",
    logLabel: "Alice Johnson",
  },
  {
    name: "Bob Brown",
    country: "USA",
    orderDate: "2024-01-06",
    id: "4",
    logLabel: "Bob Brown",
  },
  {
    name: "Mary Davis",
    country: "Canada",
    orderDate: "2024-01-06",
    id: "5",
    logLabel: "Mary Davis",
  },
  {
    name: "Tom Wilson",
    country: "Canada",
    orderDate: "2024-01-05",
    id: "6",
    logLabel: "Tom Wilson",
  },
  {
    name: "Sara Moore",
    country: "Canada",
    orderDate: "2024-01-10",
    id: "7",
    logLabel: "Sara Moore",
  },
  {
    name: "James Taylor",
    country: "Mexico",
    orderDate: "2024-01-11",
    id: "8",
    logLabel: "James Taylor",
  },
  {
    name: "Patricia White",
    country: "Mexico",
    orderDate: "2024-01-01",
    id: "9",
    logLabel: "Patricia White",
  },
  {
    name: "Michael Harris",
    country: "Mexico",
    orderDate: "2024-01-08",
    id: "10",
    logLabel: "Michael Harris",
  },
];
